### ISSUE TITLE
Cleartext traffic is not permitted on Android 9+ by default 

### ISSUE THREAD

**Issue by dupovalo** [carrotquest/android-sdk#1]
It seems that the library uses http rather than https (for some requests at least). Http is not permitted on Android 9+ by default. So, an app is to be configured appropriately.

It's not a good practice to define usesClearTextTraffic for the app globally, so specific domains should be listed in network security config.

Can you please share a list of domains used by the library, or give us a complete network security configuration xml?

**Comment by botalov** [comment]
@dupovalo 
Library uses only https. Please, repeat the problem on version 1.0.22 and in case of success, please, provide with more details (screenshots, logs, example of the code)

**Comment by dupovalo** [comment]
Checked on 1.0.23.
The problem is fixed.
An app doesn't require clear-text traffic configuration in order to CQ to work properly.
