### ISSUE TITLE
Can't install because provider name io.carrotquest.cqandroid_lib.provider (in package ....) is already used by carrotquest.mobil.inkov.carrotquest]

### ISSUE THREAD

**Issue by Dimoshka** [carrotquest/android-sdk#12]
Последняя версия плагина не совместима с предыдущими, и даже с вашим родным приложением.

 Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name io.carrotquest.cqandroid_lib.provider (in package .....) is already used by carrotquest.mobil.inkov.carrotquest]

**Comment by botalov** [comment]
Исправили в версии 1.0.36
