### ISSUE TITLE
NoSuchMethodError when try to start chat

### ISSUE THREAD

**Issue by Pomeo777** [carrotquest/android-sdk#14]
Click on FloatingButton or Carrot.openChat(context) method call always crash application with stacktrace:
java.lang.NoSuchMethodError: No virtual method centerCrop()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/~~DN-9O2F0d26t0Fu5WdPgcA==/ua.redTeam.peopleForPeople.consumer-YnIUiAdE_hQQUmnPO0cNEA==/base.apk)

**Comment by Pomeo777** [comment]
Whith Glide version do you use in your sdk?

**Comment by kva97** [comment]
Воспроизводится та же ошибка и краш приложения при попытке открыть чат через метод Carrot.openChat();
Логи краша:

I/FIAM.Display( 2229): Unbinding from activity: app.app.MainActivity

I/FIAM.Headless( 2229): Removing display event component

W/ru.frfrstaging( 2229): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)

W/ru.frfrstaging( 2229): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)

I/FloatingActionButton( 2229): Setting a custom background is not supported.

D/AndroidRuntime( 2229): Shutting down VM

E/AndroidRuntime( 2229): FATAL EXCEPTION: main

E/AndroidRuntime( 2229): Process: ru.frfrstaging, PID: 2229

E/AndroidRuntime( 2229): java.lang.NoSuchMethodError: No virtual method centerCrop()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/~~fv7EW6WCSLRfk6cvkFR2ug==/ru.frfrstaging-wHnU7Bb4z7kX8i4DADd3uA==/base.apk)

E/AndroidRuntime( 2229): at io.carrotquest_sdk.android.presentation.mvp.dialog.presenter.DialogPresenter.createEmptyAdminImageView(DialogPresenter.kt:1569)

E/AndroidRuntime( 2229): at io.carrotquest_sdk.android.presentation.mvp.dialog.presenter.DialogPresenter.attachView(DialogPresenter.kt:118)

E/AndroidRuntime( 2229): at io.carrotquest_sdk.android.presentation.mvp.dialog.view.DialogActivity.init(DialogActivity.kt:163)

E/AndroidRuntime( 2229): at io.carrotquest_sdk.android.presentation.mvp.dialog.view.DialogActivity.onCreate(DialogActivity.kt:157)

E/AndroidRuntime( 2229): at android.app.Activity.performCreate(Activity.java:8000)

E/AndroidRuntime( 2229): at android.app.Activity.performCreate(Activity.java:7984)

E/AndroidRuntime( 2229): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1312)

E/AndroidRuntime( 2229): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)

E/AndroidRuntime( 2229): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3602)

E/AndroidRuntime( 2229): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)

E/AndroidRuntime( 2229): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)

E/AndroidRuntime( 2229): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)

E/AndroidRuntime( 2229): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)

E/AndroidRuntime( 2229): at android.os.Handler.dispatchMessage(Handler.java:106)

E/AndroidRuntime( 2229): at android.os.Looper.loop(Looper.java:223)

E/AndroidRuntime( 2229): at android.app.ActivityThread.main(ActivityThread.java:7660)

E/AndroidRuntime( 2229): at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 2229): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)

E/AndroidRuntime( 2229): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

W/ru.frfrstaging( 2229): Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (unsupported, reflection, allowed)

W/ru.frfrstaging( 2229): Accessing hidden method Landroid/app/ActivityThread;->getProcessName()Ljava/lang/String; (unsupported, reflection, allowed)

**Comment by botalov** [comment]
Спасибо за внимательность. Мы изолировали Glide и проблема больше не должна повторяться. Закрываю ишью за давностью истории. Если же проблема повториться создайте, пожалуйста, новое обращение
