### ISSUE TITLE
в аппе появились краши

### ISSUE THREAD

**Issue by Ngsetest** [carrotquest/android-sdk#15]
здравствуйте, посмотрите краши
![image](https://user-images.githubusercontent.com/29040713/122057252-164faf00-cdf3-11eb-9659-4823e315c7fd.png)
![image](https://user-images.githubusercontent.com/29040713/122057314-29627f00-cdf3-11eb-8ffe-5a20e4764261.png)
![image](https://user-images.githubusercontent.com/29040713/122057368-397a5e80-cdf3-11eb-81f3-94ec044d4064.png)

**Comment by MrOlolo** [comment]
Up
Android 11. CarrotSdk 1.0.36
![image](https://user-images.githubusercontent.com/24739054/145290061-ed2a01d3-1d25-41b6-8ce3-2b4c5416f8b9.png)

**Comment by MrOlolo** [comment]
Вытащил из crashlytics полную информацию по последним ивентам с крашами:
https://gist.github.com/MrOlolo/bb8c71d9dbb4520ad6ece9e39648d375#file-crash-carrotwebviewpresenter-json
https://gist.github.com/MrOlolo/e1e7816d726c54cd0c4894197dd45898#file-crash-newmessageusecasekt-json
https://gist.github.com/MrOlolo/dac606487024205192c336238f947d9f#file-crash-pushnotificationhelper-json

**Comment by botalov** [comment]
@MrOlolo добрый день! В последних версиях SDK мы рефакторили код, в которых у вас падало SDK. Хочу спросить, обновлялись ли вы до последних версий (сейчас актуальна 1.0.41) и, если да, воспроизводится ли там эта проблема?

**Comment by MrOlolo** [comment]
@botalov добрый! Нет, на последнюю версию не обновлялись. Тогда обновим и последим еще. Отпишусь здесь по результатам

**Comment by botalov** [comment]
За давностью последних сообщений, закрываю данное ишью. Если проблема повторится на последней версии SDK, то пожалуйста создайте новое обращение.
