### ISSUE TITLE
Install failed with targetSdkVersion 31

### ISSUE THREAD

**Issue by MrOlolo** [carrotquest/android-sdk#18]
Can't install app at device with android 12:

`Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl83659079.tmp/base.apk (at Binary XML file line #302): io.carrotquest_sdk.android.presentation.mvp.notifications.SdkFirebaseMessagingService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]`

**Comment by botalov** [comment]
Fixed in latest version
