### ISSUE TITLE
Новые сообщения появляются только после перезапуска

### ISSUE THREAD

**Issue by MrOlolo** [carrotquest/android-sdk#19]
Имеются жалобы касательно загрузки новых сообщений при открытом чате.
![image](https://user-images.githubusercontent.com/24739054/147346347-3276a29d-28eb-4685-bc14-76b596d3142b.png)

**Comment by botalov** [comment]
В предыдущих релизах мы улучшили работу сообщений в режиме онлайн. Пожалуйста, обновитесь до последней версии. Закрою этот ишью за давностью проблемы. Если возникнут вопросы - создайте, пожалуйста, новый запрос
