### ISSUE TITLE
FloatingButton elevation is fixed to 10.0 px

### ISSUE THREAD

**Issue by dupovalo** [carrotquest/android-sdk#2]
That makes it impossible to place the FAB above other content if that content has elevation > than 10px (i.e. 5dp for xhdpi, 3dp for xxhdpi, 2dp for xxxhdpi and so on).

Can you please support android:elevation attribute, so the FAB's elevation will be controllable by the app itself.

Thanks in advance.

**Comment by botalov** [comment]
@dupovalo 
Can't repeat on version 1.0.22.  android:elevation parameter setting works correctly on FAB. Example:
```
<io.carrotquest_sdk.android.ui.fab.FloatingButton
    android:id="@+id/floating_button"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:elevation="21dp"
    />
```
Please use the version 1.0.22 and try to repeat this bug. If you'll be able to give more details, it would be perfect (for example, example of your code).

**Comment by dupovalo** [comment]
Checked on 1.0.23.
The problem is fixed.
