### ISSUE TITLE
Не открывается чат

### ISSUE THREAD

**Issue by NChervinska** [carrotquest/android-sdk#20]
Не открываеться чат 
Использую Dashly.openChat
Консоль выводит вот такую ошибку ` {"meta": {"status": 400, "error": "LookupError", "error_message": "Invalid lookup (Conversation): last_conversation", "model_name": "Conversation"}, "data": {}}`
Подскажите, пожалуйста, как это исправить

**Comment by botalov** [comment]
Подскажите пожалуйста, какую Dashly SDK версию используете? 
И сразу, чтобы отсеять банальные вещи, спрошу - вызываете ли `Dashly.setup(context, API_KEY, APP_ID, callbackSetup)` перед тем как пытаться открыть чат? И, если да, то что приходит в колбэк?

**Comment by NChervinska** [comment]
Использую версию 47, так как в версиях выше падает вот такой `exception`:
`/AndroidRuntime(11027): 	at io.carrotquest_sdk.android.data.service.CarrotService$21.onNext(CarrotService.java:1387)
E/AndroidRuntime(11027): 	at io.carrotquest_sdk.android.data.service.CarrotService$21.onNext(CarrotService.java:1363)
2
E/AndroidRuntime(11027): 	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
E/AndroidRuntime(11027): 	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
E/AndroidRuntime(11027): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
E/AndroidRuntime(11027): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
E/AndroidRuntime(11027): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
E/AndroidRuntime(11027): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(11027): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11027): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(11027): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
` 
Конечно, функцию `setup` вызываю, в колбэке приходит статус 200 и auth_token

**Comment by botalov** [comment]
На версии 1.0.57 такой же `exception`? Если да, можете написать более подробный кейс, когда это происходит?

**Comment by NChervinska** [comment]
Да, на версии 1.0.57 тоже самое. Ошибка появляется в `callback`, в функции `onResponse`. Если убрать callback, то `exceptoin`а нет. Но чат всеравно не открывается (вечная загрузка), с сервера приходит 400.
Раньше мы использовали Carrot, и все работало. Когда заменили Carrot на Dashly, чат перестал открываться. (apiKey, appId, authKey тоже поменяли )

**Comment by NChervinska** [comment]
На верисии 1.0.57 вот такое:
unable to load android socket classes
```
W/OkHttp  (10900): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  (10900): 	at java.lang.Class.getMethod(Class.java:2103)
W/OkHttp  (1090unable to load android socket classes
W/OkHttp  (10900): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  (10900): 	at java.lang.Class.getMethod(Class.java:2103)
W/OkHttp  (10900): 	at java.lang.Class.getDeclaredMethod(Class.java:2081)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  (10900): 	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  (10900): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  (10900): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  (10900): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  (10900): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  (10900): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  (10900): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule.provideRetrofit(RetrofitModule.java:99)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule_ProvideRetrofitFactory.provideRetrofit(RetrofitModule_ProvideRetrofitFactory.java:37)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule_ProvideRetrofitFactory.get(RetrofitModule_ProvideRetrofitFactory.java:28)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule_ProvideRetrofitFactory.get(RetrofitModule_ProvideRetrofitFactory.0): 	at java.lang.Class.getDeclaredMethod(Class.java:2081)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  (10900): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  (10900): 	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  (10900): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  (10900): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  (10900): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  (10900): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  (10900): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  (10900): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule.provideRetrofit(RetrofitModule.java:99)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule_ProvideRetrofitFactory.provideRetrofit(RetrofitModule_ProvideRetrofitFactory.java:37)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule_ProvideRetrofitFactory.get(RetrofitModule_ProvideRetrofitFactory.java:28)
W/OkHttp  (10900): 	at io.carrotquest.cqandroid_lib.di.RetrofitModule_ProvideRetrofitFactory.get(RetrofitModule_ProvideRetrofitFactory.
```

**Comment by viacheslav-proarea** [comment]
@botalov Абсолютно аналогичная ситуация. Подскажите, пожалуйста, есть ли продвижение в вопросе?

**Comment by Alond** [comment]
@NChervinska @viacheslav-proarea  уточните версию android и версию библиотеки okhttp

**Comment by NChervinska** [comment]
@Alond библиотеку okhttp не использую, но использую retrofit (он вроде содержит okhttp)
Версия андроид 11

**Comment by NChervinska** [comment]
Ошибку с библиотекой okhttp исправить не сложно (необходимо добавить пару строк в build.gradle)
![photo_2022-07-25_17-55-31](https://user-images.githubusercontent.com/64692640/180808642-d4b5cac1-528c-4a08-a1f8-737d61d9c9b9.jpg)

Чат все равно не прогружается, в консоле эксепшенов нет

**Comment by NChervinska** [comment]
В консоле есть вот такое:```
 --> GET https://api.dashly.app/v1/conversations/last_conversation
I/okhttp.OkHttpClient(10994): --> END GET
I/okhttp.OkHttpClient(10994): <-- 400 https://api.dashly.app/v1/conversations/last_conversation?_nonce=f7f4e50a6f7d437b82852c0555f&user_agent=android_sdk&id_as_string=1&auth_token=user.1175743071107616.4701-4ff8a9d78491c374df3343cc4.35347651c96481bcf52e239aff66788c82471a9f (203ms)
```

**Comment by NChervinska** [comment]
Проблема исправлена в новой версии
