### ISSUE TITLE
Приложение падает с ошибкой FATAL EXCEPTION при установке токена (Flutter v3.3.1)

### ISSUE THREAD

**Issue by Pelmeshka102** [carrotquest/android-sdk#22]
При переходе с старого flutter v2.10.1 на новый v3.3.1 при попытки установки токена приложение завершает работу с FATAL EXCEPTION

[text.txt](https://github.com/carrotquest/android-sdk/files/9622551/text.txt)

**Comment by botalov** [comment]
Добрый день! Прошу прощения за долгий ответ. Проблему решили, фикс попадет в следующий релиз (ориентировочно, он будет в течении недели)

**Comment by Pelmeshka102** [comment]
Здравствуйте, есть новости по этой задаче?

**Comment by botalov** [comment]
Добрый день! Попробуйте обновиться до версии 1.0.60, релиз которой был на днях.

**Comment by botalov** [comment]
Закрываю issue, так как в течении долгого времени не было фидбека. Если проблема повторяется, пожалуйста создайте новый запрос.
