### ISSUE TITLE
Ошибка в релизной сборке

### ISSUE THREAD

**Issue by riyga25** [carrotquest/android-sdk#24]
1.0.61-commonRelease
В дебаг сборке работает нормально, а релизной падение при ините.

В приложении включен proguard
```kotlin
isMinifyEnabled = true
isShrinkResources = true
```

инит чата 
```kotlin
Carrot.setup(
  context,
  CARROT_CHAT_API_KEY,
  CARROT_CHAT_APP_ID,
  object : CarrotSDK.Callback<Boolean> {
    override fun onResponse(p0: Boolean?) {
      Carrot.auth("user", CARROT_CHAT_USER_AUTH_KEY, carrotAuthCallback)
    }
    override fun onFailure(p0: Throwable?) {}
  }
)
```

ошибка
`
java.lang.IllegalArgumentException: Unable to create call adapter for class ug.k
    for method a.e
    retrofit2.Utils.methodError(Utils.java:54)
    retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:116)
    retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:67)
    retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
    retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
    retrofit2.Retrofit$1.invoke(Retrofit.java:160)
    java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    $Proxy8.e(:0)
    io.carrotquest.cqandroid_lib.CarrotLib.connect(CarrotLib.java:107)
    io.carrotquest_sdk.android.data.service.CarrotService.init(CarrotService.java:185)
    io.carrotquest_sdk.android.core.main.CarrotSDK.commonSetup(CarrotSDK.java:199)
    io.carrotquest_sdk.android.core.main.CarrotSDK.setup(CarrotSDK.java:149)
    ru.smartinvestors.ae.ui.mainFlow.profile.help.HelpScreen$Content$1.invokeSuspend(HelpScreen.kt:96)
    kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
    androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
    androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
    android.os.Handler.handleCallback(Handler.java:942)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loopOnce(Looper.java:226)
    android.os.Looper.loop(Looper.java:313)
    android.app.ActivityThread.main(ActivityThread.java:8741)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.IllegalStateException: Observable return type must be parameterized as Observable<Foo> or Observable<? extends Foo>
    retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory.get(RxJava2CallAdapterFactory.java:118)
    retrofit2.Retrofit.nextCallAdapter(Retrofit.java:253)
    retrofit2.Retrofit.callAdapter(Retrofit.java:237)
    retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:114)
    retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:67)
    retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
    retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
    retrofit2.Retrofit$1.invoke(Retrofit.java:160)
    java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    $Proxy8.e(:0)
    io.carrotquest.cqandroid_lib.CarrotLib.connect(CarrotLib.java:107)
    io.carrotquest_sdk.android.data.service.CarrotService.init(CarrotService.java:185)
    io.carrotquest_sdk.android.core.main.CarrotSDK.commonSetup(CarrotSDK.java:199)
    io.carrotquest_sdk.android.core.main.CarrotSDK.setup(CarrotSDK.java:149)
`

При попытке использовать 1.0.62-commonRelease падает прям всё приложение со старта.

**Comment by botalov** [comment]
Добрый день! Прошу прощения за долгий ответ. В последних версиях, начиная с 1.0.66 данная проблема решена. Если возникнут вопросы, создайте пожалуйста новый issue
