### ISSUE TITLE
Не запускается чат в ReactNative

### ISSUE THREAD

**Issue by shuraman69** [carrotquest/android-sdk#25]
Не отрабатывает Carrot.openChat из-за ошибки 
`calling startactivity() from outside of an activity context requires the flag_activity_new_task flag`

Не нашел ничего лучше, чем скопировать код из метода openChat в классе CarrotSDK и вызывать его вручную из своих модулей. 

Это проблема библиотеки или я что-то не так сделал?

**Comment by botalov** [comment]
Добрый день! Прошу прощения за долгий ответ. Мы официально не поддерживаем работу SDK в приложениях на ReactNative. Но, если вы дадите больше информации в виде, например, тестового приложения, на котором воспроизводится проблема, мы постараемся помочь с решением.

**Comment by HardKot** [comment]
Аналогичная проблема. Через метод в объект, такая же ошибка. Через Intent, что-то двигается 

![Screenshot_20240319_001543](https://github.com/carrotquest/android-sdk/assets/49830207/b4adfb3c-e639-4a74-ab67-e7d6e23be7d5)

```
@ReactMethod
    fun openChat() {
        context.startActivity(Intent(context.applicationContext, DialogActivity::class.java).apply {
            putExtra("CONVERSATION_ID_ARG", "last_conversation")
            setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        })
    }
```

**Comment by maxzinovev** [comment]
Есть ли решение данное проблемы?
