### ISSUE TITLE
Crash due to connection error (in case of Internet is not available) 

### ISSUE THREAD

**Issue by dupovalo** [carrotquest/android-sdk#3]
Version:
1.0.23-commonRelease

Stack trace:

> io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.net.ConnectException: Failed to connect to /192.168.1.190:8888
>  	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
>  	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
>  	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
>  	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:117)
>  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
>  	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:72)
>  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:56)
>  	at io.reactivex.Observable.subscribe(Observable.java:12246)
>  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
>  	at io.reactivex.Observable.subscribe(Observable.java:12246)
>  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
>  	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
>  	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
>  	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
>  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
>  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>  	at java.lang.Thread.run(Thread.java:764)
>  Caused by: java.net.ConnectException: Failed to connect to /192.168.1.190:8888
>  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:248)
>  	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:218)
>  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
>  	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
>  	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
>  	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
>  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
>  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
>  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
>  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
>  	at io.carrotquest.cqandroid_lib.di.RetrofitModule.lambda$provideRetrofit$0$RetrofitModule(RetrofitModule.java:62)
>  	at io.carrotquest.cqandroid_lib.di.-$$Lambda$RetrofitModule$cDDt-9oXf7IFruMzmnH_0IhxjVU.intercept(Unknown Source:2)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
>  	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
>  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
>  	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
>  	at okhttp3.RealCall.execute(RealCall.java:92)
>  	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
>  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
>  	... 12 more
>  Caused by: java.net.ConnectException: failed to connect to /192.168.1.190 (port 8888) from /:: (port 0) after 10000ms: connect failed: ENETUNREACH (Network is unreachable)
>  	at libcore.io.IoBridge.connect(IoBridge.java:137)
>  	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
>  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
>  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
>  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
>  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
>  	at java.net.Socket.connect(Socket.java:621)
>  	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
>  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
>  	... 39 more
>  Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
>  	at libcore.io.Linux.connect(Native Method)
>  	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:118)
>  	at libcore.io.IoBridge.connectErrno(IoBridge.java:168)
>  	at libcore.io.IoBridge.connect(IoBridge.java:129)
>  	... 47 more

**Comment by dupovalo** [comment]
It crashes at any arbitrary time, but it's probably related to FloatingButton.
So, I have a FloatingButton in two activities. First activity starts fine (with internet connection). Then I turn off Wi-Fi (or cellular) and go to the second activity. It crashes right away.

**Comment by botalov** [comment]
@dupovalo 
Thank you for finding such an important problem. We'll fix this bug in version 1.0.24

**Comment by dupovalo** [comment]
The bug is fixed in v 1.0.24-commonRelease.

**Comment by dupovalo** [comment]
Let me reopen the issue since there is a similar crash in 1.0.24-commonRelease.

> io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | **java.net.SocketTimeoutException: timeout**
> 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
> 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
> 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
> 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
> 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:72)
> 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:56)
> 	at io.reactivex.Observable.subscribe(Observable.java:12285)
> 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
> 	at io.reactivex.Observable.subscribe(Observable.java:12285)
> 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
> 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
> 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
> 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:764)
> **Caused by: java.net.SocketTimeoutException: timeout**
> 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
> 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
> 	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
> 	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
> 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at io.carrotquest.cqandroid_lib.di.RetrofitModule.lambda$provideRetrofit$0$RetrofitModule(RetrofitModule.java:62)
> 	**at io.carrotquest.cqandroid_lib.di.-$$Lambda$RetrofitModule$cDDt-9oXf7IFruMzmnH_0IhxjVU.intercept(Unknown Source:2)**
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
> 	at okhttp3.RealCall.execute(RealCall.java:92)
> 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
> 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
> 	... 12 more

**Comment by botalov** [comment]
@dupovalo 
Sorry, we couldn't repeat the problem. But we worked to make the app more stable. Please try to use the new version (1.0.25) of SDK and see if the problem appears. In case if the problem repeats, please discribe for us to try to find it again.

**Comment by dupovalo** [comment]
Tried 1.0.25-commonRelease for a while and see SocketTimeoutException is properly caught with no crash. So, closing the issue. Thanks.
