### ISSUE TITLE
Ошибка при попытке отправить сообщение

### ISSUE THREAD

**Issue by ArtorNado** [carrotquest/android-sdk#4]
Пытаюсь интегрировать ваш чат в андройд приложение. Когда открываю чат и отправляю сообщение, получаю такую ошибку:
java.lang.IndexOutOfBoundsException: getChars (-1 ... 0) starts before 0
Перед этим получаю уведомление android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
Если открывать чат, потом историю диалогов, потом переключиться на чат обратно и попробовать что-либо написать, ошибки не будет

**Comment by botalov** [comment]
Пару вопросов для локализации проблемы:
* Версия SDK 1.0.26?
* Чат вы открываете при помощи нашей Floating Action Button или при помощи вызова метода Carrot.openChat(context)?
@ArtorNado

**Comment by ArtorNado** [comment]
1. Версия 1.0.26
2. Чат открывается при помощи Carrot.openChat(context)

**Comment by botalov** [comment]
@ArtorNado 
Спасибо за описание проблемы. Задачу приняли в работу. Займусь ей в ближайшее время и отпишусь, когда будет какой-либо прогресс.

**Comment by botalov** [comment]
@ArtorNado
Проблему удалось повторить и локализовать. Будет поправлено в ближайшем релизе (ориентировочно на след. неделе).

**Comment by botalov** [comment]
@ArtorNado Зарелизили новую версию - 1.0.27-commonRelease (https://github.com/carrotquest/android-sdk/commit/4a444e224c350b828ccf582944ce99104b08b386). Буду благодарен, если после проверки вы отпишетесь сюда)

**Comment by UlugbekSattarov** [comment]
Добрый день, у меня возникла проблема с FAB в xml
<img width="679" alt="image" src="https://user-images.githubusercontent.com/30044002/106556836-4e400f00-6542-11eb-842e-3793eec37cb9.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/30044002/106556873-5ef08500-6542-11eb-95ec-d72203769d31.png">

**Comment by UlugbekSattarov** [comment]
не показывает FAB

**Comment by botalov** [comment]
По вопросу с кнопкой чата отписался тут - https://github.com/carrotquest/android-sdk/issues/6.
