### ISSUE TITLE
Ошибка в релиз сборке

### ISSUE THREAD

**Issue by valer4ik87** [carrotquest/android-sdk#5]
в релизной сборке проблемы с отображением информации, точнее она не отображается, пустые диалоги, при этом сообщения на сервер уходят, возможно надо в proguard что то добавить

Можете дать настройки ProGuarda?

**Comment by botalov** [comment]
@valer4ik87 
Можете уточнить, каким способом вы открываете диалог? При помощи нашей Floating Action Button или при помощи вызова метода Carrot.openChat(context)?

**Comment by valer4ik87** [comment]
вызываю метод

**Comment by valer4ik87** [comment]
уточню еще, что собираю с включенным proguardом, т.е. minifyEnabled true

**Comment by otis22** [comment]
@botalov добрый день, получается найти причину? Нам стоит ждать или искать другой чат?

**Comment by botalov** [comment]
@valer4ik87 Добрый день. Сегодня будет релиз, в нем мы поправили этот баг. Прошу прощения за долгий ответ.

**Comment by botalov** [comment]
@otis22 @valer4ik87 Зарелизили (https://github.com/carrotquest/android-sdk/commit/4a444e224c350b828ccf582944ce99104b08b386). Новая версия - 1.0.27-commonRelease. Буду благодарен, если вы отпишетесь сюда после проверки того, что баг исправлен)

**Comment by otis22** [comment]
@botalov передал Валерию, если еще успеет перед отпуском, то в ближайшие дни отпишется.

**Comment by valer4ik87** [comment]
всё, пофикшено
