### ISSUE TITLE
not showing fab in xml

### ISSUE THREAD

**Issue by UlugbekSattarov** [carrotquest/android-sdk#6]
Добрый день, у меня возникла проблема с FAB в xml
не показывает FAB

![](https://user-images.githubusercontent.com/30044002/106556836-4e400f00-6542-11eb-842e-3793eec37cb9.png)

![](https://user-images.githubusercontent.com/30044002/106556873-5ef08500-6542-11eb-95ec-d72203769d31.png)

**Comment by botalov** [comment]
В свойство `app:cq_icon_fab` нужно записывать векторное изображение из папки `drawable`, а не цвет. Тогда должно все сработать. Если не получится, напишите нам. 
 Цвет кнопки можно менять в настройках самого сервиса - Настройки -> Чат -> Основные настройки чата -> Цвет активных элементов чата. Тогда при следующей инициализации SDK цвет кнопки а также цвет других элементов подтянется с сервера
