### ISSUE TITLE
При использовании SDK не видна история диалогов пользователя

### ISSUE THREAD

**Issue by otis22** [carrotquest/android-sdk#7]
Отправлялись и попапы и сообщения пользователю 

https://prnt.sc/y08lu7 https://prnt.sc/y0a3pw

Но в приложении история диалогов пустая. https://ibb.co/p23qTsJ

 Carrot.openChat(context);

**Comment by otis22** [comment]
[video](https://drive.google.com/file/d/1GXoPxd058Mp4QTEVcrkF6DJbrm8ZYHG3/view?usp=sharing) Видео, я писал для нашего разработчика, но на нем видно как воспроизвести все проблемы.

**Comment by botalov** [comment]
Здравствуйте, @otis22! То, что нет истории и при этом висит бабл о непрочитанном сообщении - эту проблему буду исследовать. Скажите пожалуйста, какую версию SDK используете?
Но, помимо этого, нужно сказать, что этот попап в любом случае не придет в приложение, т.к. он предназначен для показа пользователем с web'a. Напишите пожалуйста нам в техподдержку, скажите им свой AppId и попросите разблокировать для вас возможность отправлять автосообщения пользователем SDK)

**Comment by otis22** [comment]
@botalov попап хорошо, а просто сообщения будут приходить?

**Comment by otis22** [comment]
@botalov   версию аппа уточнит программист, чуть позже в конфиге так  maven { url "https://raw.github.com/carrotquest/android-sdk/beta" }

Думаю, что последняя. Но лушче дождитесь комментарий от программиста

**Comment by valer4ik87** [comment]
на видео 1.0.27
но на 1.0.28 проблема воспроизодилась

**Comment by botalov** [comment]
> @botalov попап хорошо, а просто сообщения будут приходить?

Смотря какие сообщения вы имеете ввиду) Если вы про автосообщения, то вот только последние 3 типа будут приходить в SDK. 
![image](https://user-images.githubusercontent.com/15613261/106899729-864c7b00-6717-11eb-859a-14b08bff36e2.png)
Хотя по поводу первого типа я уточню у наших продактов, работает ли это сейчас так, как планировалось. По результатам отпишусь тут.

**Comment by botalov** [comment]
> на видео 1.0.27
> но на 1.0.28 проблема воспроизодилась

Сейчас актальная версия 1.0.29. Если есть возможность, проверьте эту версию пожалуйста. Там как раз были изменения  в списке диалогов.

**Comment by otis22** [comment]
> > @botalov попап хорошо, а просто сообщения будут приходить?
> 
> Смотря какие сообщения вы имеете ввиду) Если вы про автосообщения, то вот только последние 3 типа будут приходить в SDK.
> ![image](https://user-images.githubusercontent.com/15613261/106899729-864c7b00-6717-11eb-859a-14b08bff36e2.png)
> Хотя по поводу первого типа я уточню у наших продактов, работает ли это сейчас так, как планировалось. По результатам отпишусь тут.

Спасибо, теперь понятно.

**Comment by otis22** [comment]
> > на видео 1.0.27
> > но на 1.0.28 проблема воспроизодилась
> 
> Сейчас актальная версия 1.0.29. Если есть возможность, проверьте эту версию пожалуйста. Там как раз были изменения в списке диалогов.

Валерий завтра в отпуск, возможно уже не на связи. Может ответить через пару недель.

**Comment by valer4ik87** [comment]
через неделю проверим на актуальной версии сдк, отпишемся

**Comment by botalov** [comment]
Так как комментариев тут не было очень давно, мы закрываем ишью. Если возникнут какие-то вопросы по данное теме, пожалуйста, создайте новый
