### ISSUE TITLE
Нет пуш уведомления при отправке попап и сообщений пользователю 

### ISSUE THREAD

**Issue by otis22** [carrotquest/android-sdk#8]
Чтобы воспроизвести: 

https://prnt.sc/y0cyzo перейти в керот в лида и при отправки сообщений выделенными кнопками юзер не получает пуш уведомление. Только если https://prnt.sc/y0d3de - перейти в диалоги и отправить сообщение в диалогах, то юзер получает пуш уведомление. 

Из-за этого бага невозможно настроить рассылку автосообщений по сценариям в мобильном приложении.

**Comment by otis22** [comment]
Попапы в мобильном прилоежнии в целом не отображаются.

**Comment by botalov** [comment]
Здравствуйте, @otis22) Стандартные автосообщения не предназначены для пользователей SDK. Для таких пользователей есть специальные автосообщения. Чтобы открыть их в интерфейсе, напишите пожалуйста в нашу поддержку (прямо в чатик на нашем сайте - https://www.carrotquest.io/) и попросите их включить автосообщения для SDK)

**Comment by otis22** [comment]
@botalov написал. Обратите внимание еще на то что Истории диалогов нет. Даже если не попапы отправлять, а просто сообщения.

**Comment by otis22** [comment]
@botalov добрались, запустили новую версию. Видна история диалогов. 
Но попапы не отправляются когда приложени свернуто. Это нормальное поведение?:

**Comment by botalov** [comment]
@otis22 Добрый день! Попап должен появиться после того, как вы откроете приложение из фона. Проследите, что не вызывается метод Carrot. deInit(), когда приложение уходит в фон. Кроме того, при отправке попапа можно поставить галочку, чтобы отправлялось пуш-уведомление о нем (как это настроить можно посмотреть тут - https://developers.carrotquest.io/push_android_sdk/). Если поведение отличается, опишите кейс подробнее пожалуйста.

**Comment by botalov** [comment]
Надеемся, что у вас больше не было проблем. Закрываем этот тред за давностью. Если будут вопросы - создайте новый ишью или напишите нам в поддержку.
